apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-grpc-deployment
  labels:
    app: go-grpc
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go-grpc
  template:
    metadata:
      labels:
        app: go-grpc
    spec:
      containers:
      - name: go-grpc
        image: dingyuanwu/477:go_grpc
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: go-grpc-service
spec:
  selector:
    app: go-grpc
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: go-grpc
spec:
  ingressClassName: nginx
  rules:
    - host: www.wdytest.com
      http:
        paths:
          - backend:
              service:
                name: go-grpc-service
                port:
                  number: 80
            path: /
            pathType: Prefix